FROM node:20-alpine

WORKDIR /app

# Copy root package files
COPY package.json package-lock.json ./

# Copy workspace package files
COPY packages/db/package.json ./packages/db/
COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/

# Install dependencies
RUN npm install

# Copy application source
COPY packages/db ./packages/db
COPY apps/web ./apps/web

# Generate Prisma Client
RUN npm run generate -w @lighthouse/db

# Build the Web
RUN npm run build -w @lighthouse/web

EXPOSE 18013

# Start the Web App
CMD ["npm", "run", "start", "-w", "@lighthouse/web"]
